<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__passpass1</name>
   <tag></tag>
   <elementGuidId>5d07f16c-f9cc-49be-9422-14961e9d096c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-pass-pass1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-pass-pass1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>630c382a-7ced-43a6-9de9-4e6a61c285be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password-field form-text required password-processed</value>
      <webElementGuid>6f2d0e17-afef-490f-b4ce-ffaa958bd4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>258f6a3d-2c5c-468e-9e2b-3c74e526f57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-pass-pass1</value>
      <webElementGuid>903c9642-a15a-406e-afd4-03f67303f18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pass[pass1]</value>
      <webElementGuid>bccc3d0a-0fe2-45c8-a11b-9c27ef3d8cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>e1398e8d-02e8-4f74-bca7-7bb19aa8c591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>0a42ab4e-397b-4325-9955-ba992da99a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-pass-pass1&quot;)</value>
      <webElementGuid>52cd7aab-c8de-48ec-9947-568233bda1ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-pass-pass1']</value>
      <webElementGuid>a9ddc80e-4b58-4476-afeb-9f4fe439cd19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-account']/div[3]/div/input</value>
      <webElementGuid>0d6ab6a9-a58c-42cd-86eb-11627332dc1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>b2534e55-bbdc-4525-81d0-047ca1b889e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'edit-pass-pass1' and @name = 'pass[pass1]']</value>
      <webElementGuid>d0edd7b2-6150-4a5d-8d62-192d04142bac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
