<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mail</name>
   <tag></tag>
   <elementGuidId>32c57c18-6703-4bca-94e5-92b195a7cacf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-mail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-mail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9191373f-11ce-4742-856a-58840b0856d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>friendly-register-mail form-text required friendly-register-processed</value>
      <webElementGuid>2c7d2cc2-0cd0-46ab-aa06-c3f0bcde5ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8dd1be3d-cd81-4a64-8f3b-7e8df1fa1e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-mail</value>
      <webElementGuid>e405c5e7-572c-4b74-868c-4518f5d13795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mail</value>
      <webElementGuid>dff41802-f9dd-422f-84f0-77ffd011376b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>37ff2aee-d894-4891-84b4-8aec1d8b6922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>254</value>
      <webElementGuid>876709aa-018d-4287-9fd1-05f76a001ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-mail&quot;)</value>
      <webElementGuid>e85f1d0b-1b22-44de-9978-caf4f8703789</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-mail']</value>
      <webElementGuid>7f8a8df2-e75a-42f4-95f4-c4690b4eb6ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-account']/div[2]/input</value>
      <webElementGuid>75fabea0-cd1b-46ab-9969-cce7abd686b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a056a0b7-e91c-4f18-8200-08ead561dbb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'edit-mail' and @name = 'mail']</value>
      <webElementGuid>a7f07618-798f-4c18-abe7-d4f8ad62a9e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
