<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field_lastnameund0value</name>
   <tag></tag>
   <elementGuidId>8b10b885-854b-4e0e-bf5b-b46cedd72ef2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-field-lastname-und-0-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-field-lastname-und-0-value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a43b365-356c-4802-bc5c-735c35c54419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-full form-text required</value>
      <webElementGuid>89e6acc4-0489-4a9e-bbea-bda321c58e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79843e3b-f534-4196-bf90-90f8179855f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-field-lastname-und-0-value</value>
      <webElementGuid>23290c2a-50cf-43d4-841b-46a570872458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_lastname[und][0][value]</value>
      <webElementGuid>22e39f0d-23d7-4038-aab6-1edd27a90092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>870a382a-404d-42b1-b6ff-50d7bda5e860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>abef6a44-543e-4d68-846c-be8dfdf6c554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-field-lastname-und-0-value&quot;)</value>
      <webElementGuid>e37a9855-6062-4b42-b64e-c824c3af7650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-field-lastname-und-0-value']</value>
      <webElementGuid>e1ce4792-8dae-406a-8965-4406f869e548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-lastname-add-more-wrapper']/div/input</value>
      <webElementGuid>ab3c7700-e69a-454e-890a-6e8efbfed963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>af975c38-e7ca-4a30-a3f4-af5aa635dc31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'edit-field-lastname-und-0-value' and @name = 'field_lastname[und][0][value]']</value>
      <webElementGuid>cd436293-2ae0-4a44-b8a8-5e0b8b4e838c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
