<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field_telephoneund0value</name>
   <tag></tag>
   <elementGuidId>f516a469-3190-48d7-ad11-7c58bd2d46eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-field-telephone-und-0-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-field-telephone-und-0-value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fbf13cdd-61ed-4e4a-84d3-137f88bca81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-full form-text required</value>
      <webElementGuid>3e2b3134-ffd8-407d-a8a9-730ccd7d2fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ba19064-cea8-473f-a841-424b9f83f078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-field-telephone-und-0-value</value>
      <webElementGuid>34787fc0-032d-4738-83c2-4dbb4eb8d03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_telephone[und][0][value]</value>
      <webElementGuid>04a8c705-64fa-467f-9034-be8228ad7388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>86ae8dbe-ec38-49bf-8271-b0a9846dd7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>a58d5754-b840-4699-b212-3b2f006e89cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-field-telephone-und-0-value&quot;)</value>
      <webElementGuid>6090147b-5042-439d-9789-ef7ead6ff728</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-field-telephone-und-0-value']</value>
      <webElementGuid>f3e6d5cd-715f-46ff-b730-770a58e8324d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-telephone-add-more-wrapper']/div/input</value>
      <webElementGuid>43c13c59-963b-4218-b2dd-c5b29c7b6da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>7fed7d0f-cad4-4203-b582-94c57ac8fbbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'edit-field-telephone-und-0-value' and @name = 'field_telephone[und][0][value]']</value>
      <webElementGuid>eb7f9abc-3996-4f94-b57c-0a549b230393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
