<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__captcha_response</name>
   <tag></tag>
   <elementGuidId>0087ab09-eafe-47b7-a2b2-5bb72a04feb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-captcha-response</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-captcha-response']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3e04aa2-ea0c-4904-8334-45ce81cd8a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83986cbe-ba36-47f4-b5fd-a3b0321671f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-captcha-response</value>
      <webElementGuid>d47b8667-653b-4075-aa71-88d3c5da9247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>captcha_response</value>
      <webElementGuid>cdf35489-d8e2-4754-9a7b-826de0df8f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>143639e9-9f54-45d1-950d-617d3930d0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>28b546dd-2fa1-4ac9-b846-808a204954df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-text required</value>
      <webElementGuid>ad5600ae-cec8-4bb4-9e57-45e777b1ab6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f2b64a3f-9a51-4aa4-90aa-b045979fb77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-captcha-response&quot;)</value>
      <webElementGuid>48253cc5-27b2-4292-91e0-11573da1cdc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-captcha-response']</value>
      <webElementGuid>e2532c19-e97c-4c5e-9a44-0f17de738a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='user-register-form']/div/fieldset[5]/div/div[2]/input</value>
      <webElementGuid>03b48aaa-3b60-4663-9a38-845664e01ff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[5]/div/div[2]/input</value>
      <webElementGuid>a5ac07f8-6343-4717-988a-d20035a9d9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'edit-captcha-response' and @name = 'captcha_response']</value>
      <webElementGuid>ba3ddb97-3669-48dd-9572-9badbe731974</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
