<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_2003</name>
   <tag></tag>
   <elementGuidId>565e465e-f3f4-4f15-9254-6a59611d5d3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit_field_dob_und_0_value_year_chosen > div.chosen-drop > ul.chosen-results > li.active-result.result-selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit_field_dob_und_0_value_year_chosen']/div/ul/li[46]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>98a939d0-0280-4380-9acd-95bd59f34914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result result-selected</value>
      <webElementGuid>30642506-fd4c-43c1-bf91-9d0931ea0547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>635b3ad7-2aff-4862-82f8-6e6db0d78f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2003</value>
      <webElementGuid>69f764ca-b8d7-4d92-9d19-f193c0b43823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_field_dob_und_0_value_year_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;active-result result-selected&quot;]</value>
      <webElementGuid>a9c1530e-0a08-4802-bf07-596877c4c6c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit_field_dob_und_0_value_year_chosen']/div/ul/li[46]</value>
      <webElementGuid>61dfa79c-e480-4ba9-b801-2097ab0869fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[13]/following::li[46]</value>
      <webElementGuid>9dd0fbab-7960-4ed9-ae9c-de9c2fee382a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[14]/preceding::li[21]</value>
      <webElementGuid>247e453d-eb71-4c7c-92f1-5d95c82c635f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[46]</value>
      <webElementGuid>02d3a297-3f64-46e3-92c4-f311737df2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '2003' or . = '2003')]</value>
      <webElementGuid>b116a9cd-1a03-43ed-9657-363a704de43b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
