<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select a value -_1</name>
   <tag></tag>
   <elementGuidId>f1f71176-9e31-433f-ac57-a177f7009d4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-field-title-und</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='edit-field-title-und']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>db069a68-fbaf-4f0d-83ed-5029021b1957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-field-title-und</value>
      <webElementGuid>8661185f-88be-4ed4-ab7e-e1b5f724fddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_title[und]</value>
      <webElementGuid>f293782f-dde7-49c1-8bb6-f6c44af62a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required</value>
      <webElementGuid>fedcd82a-e0d3-4ba6-8eb3-123f4d5d3970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select a value -นายนางนางสาวอื่นๆ</value>
      <webElementGuid>0d23525a-e92c-4dde-bfdc-47591661fe7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-field-title-und&quot;)</value>
      <webElementGuid>666e4d25-a973-4e68-a57a-e787163ce89f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit-field-title-und']</value>
      <webElementGuid>0678522d-f787-4b40-aa8a-42bfe87f06dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-field-title']/div/select</value>
      <webElementGuid>ec3fd36d-093b-48c4-ab13-026da877c1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>3ec3a213-0040-4f55-9c7e-11768aa98b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[1]</value>
      <webElementGuid>9808a9c1-bd7e-4ab7-81e3-a0333f937338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div[2]/div/select</value>
      <webElementGuid>e74baa77-a468-4be2-8f98-2d7daf2a35ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'edit-field-title-und' and @name = 'field_title[und]' and (text() = '- Select a value -นายนางนางสาวอื่นๆ' or . = '- Select a value -นายนางนางสาวอื่นๆ')]</value>
      <webElementGuid>dffcf63a-246d-49d9-b057-058c1199bfb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
