<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select a value -_1_2</name>
   <tag></tag>
   <elementGuidId>26f3bddb-9e94-450f-8fec-e16fbbb58218</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-field-officer-type-und</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='edit-field-officer-type-und']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7043010b-bfab-4984-810f-dab3b3d62cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-field-officer-type-und</value>
      <webElementGuid>d0be48d6-3daf-418f-82c9-4f0d0335fee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_officer_type[und]</value>
      <webElementGuid>124becc2-9499-4061-b8f9-2412fc8fcf6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required</value>
      <webElementGuid>ffa73a1e-e673-44b8-9308-9f61c440f945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select a value -ข้าราชการพลเรือนสามัญพนักงานองค์กรของรัฐพนักงานราชการลูกจ้างอาจารย์/ตำรวจ/ทหาร/อื่นๆนักศึกษา</value>
      <webElementGuid>8470aa48-8d99-4e89-a105-e3bab522d223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-field-officer-type-und&quot;)</value>
      <webElementGuid>eeaf4a4f-fe9c-4086-a0b3-72249fef05ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit-field-officer-type-und']</value>
      <webElementGuid>4e02cfae-28bc-4958-a2bf-9bb1a36782b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-field-officer-type']/div/select</value>
      <webElementGuid>8a9fb92d-152c-4f96-bb07-abc47e8e3757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[16]/following::select[1]</value>
      <webElementGuid>c69fd279-02d0-4898-bb8b-bd5a38490051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ประเภทและระดับ'])[1]/preceding::select[1]</value>
      <webElementGuid>dce15dda-458e-4f2c-8f4f-81e13dc73141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/div/select</value>
      <webElementGuid>e481f77a-de40-421c-9e16-6a4f0d7f92bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'edit-field-officer-type-und' and @name = 'field_officer_type[und]' and (text() = '- Select a value -ข้าราชการพลเรือนสามัญพนักงานองค์กรของรัฐพนักงานราชการลูกจ้างอาจารย์/ตำรวจ/ทหาร/อื่นๆนักศึกษา' or . = '- Select a value -ข้าราชการพลเรือนสามัญพนักงานองค์กรของรัฐพนักงานราชการลูกจ้างอาจารย์/ตำรวจ/ทหาร/อื่นๆนักศึกษา')]</value>
      <webElementGuid>9f021b3e-96ef-40e9-9562-8afa5154fce0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
