<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select a value -</name>
   <tag></tag>
   <elementGuidId>9426bff5-53e3-4164-94e1-c46f36aa9de3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-field-gender-und</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='edit-field-gender-und']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>837c7213-016e-4afd-b4ff-249c87cb4f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-field-gender-und</value>
      <webElementGuid>38e4f401-a8be-4b6f-b63d-d56ec5028a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_gender[und]</value>
      <webElementGuid>f441f744-c949-4a08-b1d7-14b5c0b87a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required</value>
      <webElementGuid>39efac7c-5577-4b39-9567-d81e2446ad6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select a value -ชายหญิง</value>
      <webElementGuid>a6242452-10f5-43ae-bf11-eaf180bc0d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-field-gender-und&quot;)</value>
      <webElementGuid>c1fc63c4-a118-4d11-8200-b96a32a85263</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit-field-gender-und']</value>
      <webElementGuid>9a5f14f1-ab81-42d7-a6eb-9e1ed5a5d381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-field-gender']/div/select</value>
      <webElementGuid>9a97e74b-8dfc-45dc-b07f-a158a9734dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>e9f1ac1f-eb9c-42ee-aaa5-2592f0bc0eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>d94c5720-e59a-4325-a9c0-8c10031a9e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div/div/select</value>
      <webElementGuid>a1453c08-0288-4367-bbdc-d593bb9f9ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'edit-field-gender-und' and @name = 'field_gender[und]' and (text() = '- Select a value -ชายหญิง' or . = '- Select a value -ชายหญิง')]</value>
      <webElementGuid>3b5e02ab-cfdb-468e-b077-82be137e71e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
