<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_JanFebMarAprMayJunJulAugSepOctNovDec</name>
   <tag></tag>
   <elementGuidId>ee48e00d-3631-4bb0-8e80-07cab33d3554</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-field-dob-und-0-value-month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='edit-field-dob-und-0-value-month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fa1c6f54-b994-4d74-bd00-0917b2eec826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>date-clear form-select required</value>
      <webElementGuid>fd52003a-e8fd-4332-ae83-aa9b3248ee4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-field-dob-und-0-value-month</value>
      <webElementGuid>0b5a2d63-0d3a-45cb-8606-7dfcddaf4245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_dob[und][0][value][month]</value>
      <webElementGuid>fdc2fc4d-edcf-4eda-b911-a02716e0da93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JanFebMarAprMayJunJulAugSepOctNovDec</value>
      <webElementGuid>2dae4d3d-c8af-4d61-a537-a73b28845921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-field-dob-und-0-value-month&quot;)</value>
      <webElementGuid>a716232d-381e-4b9d-896c-7f8b2cf36c35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit-field-dob-und-0-value-month']</value>
      <webElementGuid>ff3299bd-b4ed-4074-90d4-a847da7558ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-field-dob-und-0-value']/div[2]/div/select</value>
      <webElementGuid>ce30e352-c6b9-42dd-bbcc-8064fc7723f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/following::select[1]</value>
      <webElementGuid>7ef74839-ed5d-46d9-a06e-7647a73a3a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[13]/preceding::select[1]</value>
      <webElementGuid>69818ba2-48c5-4fa7-b852-ddd779143592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/select</value>
      <webElementGuid>d3feef1f-7295-4687-930c-29122204b6ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'edit-field-dob-und-0-value-month' and @name = 'field_dob[und][0][value][month]' and (text() = 'JanFebMarAprMayJunJulAugSepOctNovDec' or . = 'JanFebMarAprMayJunJulAugSepOctNovDec')]</value>
      <webElementGuid>a8c29aaa-b805-49e3-aeda-4428c294fb0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
